export const styles = {
  centerPage: {
    minHeight: 300,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg)",
  },
  app: {
    display: "flex",
    minHeight: "100%",
    border: "1px solid var(--line)",
  },
  sidebar: {
    width: 68,
    flexShrink: 0,
    background: "var(--ink)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "16px 0",
    gap: 20,
    borderRight: "1px solid var(--line)",
  },
  sidebarBrand: { marginBottom: 4 },
  sidebarNav: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 14,
  },
  navItemActive: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    color: "#fff",
    fontSize: 8.5,
    textAlign: "center",
    lineHeight: 1.2,
    width: 56,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  navItemButton: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    color: "#B8C0CA",
    fontSize: 8.5,
    textAlign: "center",
    lineHeight: 1.2,
    width: 56,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  navItemDisabled: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    color: "#5B6472",
    fontSize: 8.5,
    textAlign: "center",
    lineHeight: 1.2,
    width: 56,
    cursor: "default",
  },
  page: {
    flex: 1,
    fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
    color: "var(--ink)",
    background: "var(--bg)",
    minHeight: "100%",
    padding: "22px 26px 34px",
    maxWidth: 1080,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 20,
  },
  brand: { display: "flex", alignItems: "center", gap: 10, flex: 1 },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 0,
    background: "var(--ink)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'IBM Plex Mono', monospace",
    fontWeight: 600,
    fontSize: 12,
  },
  brandTitle: { fontWeight: 700, fontSize: 16 },
  brandSub: {
    fontSize: 11.5,
    color: "var(--ink-soft)",
    fontFamily: "'IBM Plex Mono', monospace",
    marginTop: 1,
  },
  ghostBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 14px",
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
    color: "var(--ink)",
    fontSize: 12.5,
    fontWeight: 500,
    cursor: "pointer",
  },
  uploadZone: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "60px 30px",
    borderRadius: 0,
    border: "1.5px dashed var(--line)",
    background: "var(--surface)",
    cursor: "pointer",
    textAlign: "center",
  },
  uploadZoneActive: { borderColor: "var(--blue)", background: "#EAF1F7" },
  uploadTitle: { fontWeight: 600, fontSize: 15, marginTop: 6 },
  uploadSub: { fontSize: 12.5, color: "var(--ink-soft)", maxWidth: 360 },
  statsRow: { display: "flex", gap: 12, marginBottom: 18 },
  rfqNote: {
    display: "flex",
    gap: 8,
    background: "#EAF1F7",
    border: "1px solid #BFD4E6",
    color: "#2F5D8A",
    padding: "10px 12px",
    fontSize: 12,
    lineHeight: 1.5,
    marginBottom: 16,
  },
  rfqStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--ink-soft)",
    marginBottom: 14,
  },
  rfqPreview: {
    background: "var(--surface)",
    border: "1px solid var(--line)",
    padding: "16px 20px 20px",
  },
  rfqPreviewHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 600,
    marginBottom: 16,
    color: "var(--ink)",
  },
  rfqPreviewHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  rfqPreviewDocHeader: {
    fontSize: 11,
    fontFamily: "'IBM Plex Mono', monospace",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    color: "var(--ink-soft)",
    margin: "0 0 12px",
  },
  rfqLayout: {
    display: "grid",
    gridTemplateColumns: "360px 1fr",
    gap: 24,
    alignItems: "start",
  },
  rfqLeftCol: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  rfqRightCol: {
    position: "sticky",
    top: 20,
    background: "var(--surface)",
    border: "1px solid var(--line)",
    padding: "16px 18px 20px",
  },
  rfqFileBar: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "8px 11px",
    background: "var(--surface)",
    border: "1px solid var(--line)",
    fontSize: 12,
    color: "var(--ink-soft)",
  },
  rfqFileBarName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rfqFieldsLabel: {
    fontSize: 11,
    fontFamily: "'IBM Plex Mono', monospace",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    color: "var(--ink-soft)",
    margin: "10px 0 2px",
  },
  primaryBtn: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "9px 16px",
    border: "none",
    background: "var(--blue)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },
  dashToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  filterChips: { display: "flex", gap: 6 },
  filterChip: {
    padding: "6px 12px",
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
    color: "var(--ink-soft)",
    fontSize: 12,
    cursor: "pointer",
  },
  filterChipActive: {
    background: "var(--ink)",
    color: "#fff",
    borderColor: "var(--ink)",
  },
  matchesBox: {
    background: "var(--surface)",
    border: "1px solid var(--line)",
    borderRadius: 0,
    padding: "12px 14px",
    marginBottom: 16,
  },
  matchesLabel: {
    fontSize: 11,
    fontFamily: "'IBM Plex Mono', monospace",
    color: "var(--ink-soft)",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 8,
  },
  matchesList: { display: "flex", flexDirection: "column", gap: 2 },
  matchItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    textAlign: "left",
    padding: "7px 8px",
    border: "none",
    borderRadius: 0,
    background: "transparent",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  matchLabel: { fontSize: 13, color: "var(--ink)" },
  matchCategory: {
    fontSize: 11,
    color: "var(--ink-soft)",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  statCard: {
    background: "var(--surface)",
    border: "1px solid var(--line)",
    borderRadius: 0,
    padding: "12px 18px",
    minWidth: 140,
  },
  statLabel: { fontSize: 11.5, color: "var(--ink-soft)" },
  statValue: { fontSize: 22, fontWeight: 700, marginTop: 2 },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 10,
  },
  card: {
    textAlign: "left",
    background: "var(--surface)",
    border: "1px solid var(--line)",
    borderRadius: 0,
    padding: "12px 14px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8 },
  cardName: { fontWeight: 600, fontSize: 13.5 },
  cardBadge: {
    fontSize: 10.5,
    padding: "2px 8px",
    borderRadius: 0,
    whiteSpace: "nowrap",
    fontWeight: 500,
  },
  cardMeta: { fontSize: 11, color: "var(--ink-soft)", marginTop: 6 },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    border: "none",
    background: "transparent",
    color: "var(--ink-soft)",
    fontSize: 12.5,
    cursor: "pointer",
    padding: 0,
  },
  detailTitle: { fontWeight: 700, fontSize: 16, flex: 1 },
  detailActions: { display: "flex", alignItems: "center", gap: 8 },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
  },
  searchInput: {
    border: "none",
    background: "transparent",
    fontSize: 12.5,
    outline: "none",
    width: 180,
  },
  ghostBtnSmall: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 11px",
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
    color: "var(--ink)",
    fontSize: 12,
    cursor: "pointer",
  },
  viewToggle: {
    display: "flex",
    border: "1px solid var(--line)",
    borderRadius: 0,
    overflow: "hidden",
  },
  viewToggleBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    border: "none",
    background: "var(--surface)",
    color: "var(--ink-soft)",
    cursor: "pointer",
  },
  viewToggleBtnActive: {
    background: "var(--ink)",
    color: "#fff",
  },
  listDetailWrap: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: 0,
    background: "var(--surface)",
    border: "1px solid var(--line)",
    borderRadius: 0,
    overflow: "hidden",
    minHeight: 420,
  },
  listPane: {
    borderRight: "1px solid var(--line)",
    maxHeight: 560,
    overflowY: "auto",
  },
  listCount: {
    padding: "10px 14px",
    fontSize: 11,
    color: "var(--ink-soft)",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  listItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "9px 14px",
    border: "none",
    borderLeft: "2px solid transparent",
    background: "transparent",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  listItemActive: {
    borderLeft: "2px solid var(--blue)",
    background: "#EAF1F7",
  },
  listItemPrimary: { fontSize: 13, fontWeight: 500, color: "var(--ink)" },
  listItemSecondary: { fontSize: 11.5, color: "var(--ink-soft)", marginTop: 2 },
  loadMoreBtn: {
    display: "block",
    width: "calc(100% - 20px)",
    margin: "8px 10px",
    padding: "7px",
    borderRadius: 0,
    border: "1px dashed var(--line)",
    background: "transparent",
    color: "var(--ink-soft)",
    fontSize: 11.5,
    cursor: "pointer",
  },
  detailPane: { padding: "20px 24px", overflowY: "auto", maxHeight: 560 },
  detailPlaceholder: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    color: "var(--ink-soft)",
    fontSize: 13,
    minHeight: 300,
  },
  detailPaneTitle: { fontWeight: 700, fontSize: 17 },
  detailPaneSub: { fontSize: 12.5, color: "var(--ink-soft)", marginBottom: 18 },
  fieldGrid: { display: "flex", flexDirection: "column", gap: 12 },
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "140px 1fr",
    gap: 14,
    alignItems: "start",
  },
  fieldLabel: {
    fontSize: 11,
    fontFamily: "'IBM Plex Mono', monospace",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    color: "var(--ink-soft)",
    paddingTop: 8,
  },
  fieldValue: {
    width: "100%",
    border: "1px solid var(--line)",
    background: "var(--bg)",
    padding: "7px 10px",
    borderRadius: 0,
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--ink)",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  fieldValueRow: { display: "flex", gap: 6, alignItems: "flex-start" },
  copyBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    flexShrink: 0,
    marginTop: 1,
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
    color: "var(--ink-soft)",
    cursor: "pointer",
  },
  tableWrap: {
    background: "var(--surface)",
    border: "1px solid var(--line)",
    borderRadius: 0,
    overflowX: "auto",
    maxHeight: 560,
    overflowY: "auto",
  },
  table: { width: "auto", tableLayout: "auto", borderCollapse: "collapse", fontSize: 12 },
  th: {
    textAlign: "left",
    padding: "9px 14px 9px 9px",
    fontSize: 10,
    fontFamily: "'IBM Plex Mono', monospace",
    textTransform: "uppercase",
    letterSpacing: 0.2,
    color: "var(--ink-soft)",
    borderBottom: "1px solid var(--line)",
    whiteSpace: "nowrap",
    position: "sticky",
    top: 0,
    background: "var(--surface)",
  },
  tr: { borderBottom: "1px solid var(--line)" },
  td: { padding: "3px 5px" },
  cellEditable: {
    display: "inline-block",
    minWidth: 24,
    maxWidth: 420,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    border: "1px solid transparent",
    background: "transparent",
    padding: "5px 8px",
    fontSize: 12,
    fontFamily: "'IBM Plex Mono', monospace",
    color: "var(--ink)",
    outline: "none",
    cursor: "text",
  },
  cellInput: {
    width: "100%",
    border: "1px solid transparent",
    background: "transparent",
    padding: "5px 6px",
    borderRadius: 0,
    fontSize: 12,
    fontFamily: "'IBM Plex Mono', monospace",
    color: "var(--ink)",
  },
  emptySearch: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    padding: "30px 0",
    color: "var(--ink-soft)",
    fontSize: 13,
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 12,
  },
  pageBtn: {
    padding: "6px 12px",
    borderRadius: 0,
    border: "1px solid var(--line)",
    background: "var(--surface)",
    fontSize: 12,
    cursor: "pointer",
  },
  pageInfo: { fontSize: 11.5, color: "var(--ink-soft)" },

  cbeBlocks: { display: "flex", flexDirection: "column", gap: 14, marginTop: 16 },
  cbeVendorCard: {
    background: "var(--surface)",
    border: "1px solid var(--line)",
    padding: "12px 14px 14px",
  },
  cbeVendorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    paddingBottom: 10,
    borderBottom: "1px solid var(--line)",
  },
  cbeVendorFile: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    fontFamily: "'IBM Plex Mono', monospace",
    color: "var(--ink-soft)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cbeSourceTag: {
    fontSize: 9.5,
    padding: "1px 6px",
    background: "#EAF1F7",
    color: "var(--blue)",
    fontFamily: "'IBM Plex Mono', monospace",
    flexShrink: 0,
  },
  cbeSelect: {
    fontSize: 12.5,
    padding: "6px 8px",
    border: "1px solid var(--line)",
    background: "var(--surface)",
    color: "var(--ink)",
    minWidth: 220,
  },
  cbeSelectEmpty: {
    borderColor: "#C98A2C",
    background: "#FAEEDA",
  },
  cbeSelectAmbiguous: {
    borderColor: "#C98A2C",
  },
  cbeMultiPicker: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    maxHeight: 140,
    overflowY: "auto",
    padding: "6px 8px",
    border: "1px solid #C98A2C",
    background: "#FFFBF3",
    fontSize: 12,
  },
  cbeMultiOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    cursor: "pointer",
    lineHeight: 1.3,
  },
  cbeItemList: { display: "flex", flexDirection: "column", gap: 8 },
  cbeItemRow: {
    display: "grid",
    gridTemplateColumns: "16px 1fr 280px 90px",
    gap: 10,
    alignItems: "start",
  },
  cbeItemDesc: {
    fontSize: 12.5,
    color: "var(--ink)",
    paddingTop: 7,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cbePriceInput: {
    fontSize: 12.5,
    fontFamily: "'IBM Plex Mono', monospace",
    padding: "6px 8px",
    border: "1px solid var(--line)",
    background: "var(--bg)",
    color: "var(--ink)",
    textAlign: "right",
  },
  cbeDownloadRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 4,
  },
  cbeDownloadHint: { fontSize: 12, color: "var(--ink-soft)" },
};
